name: neuman_env
channels:
  - pytorch3d
  - bottler
  - iopath
  - fvcore
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda=11.7
  - fvcore
  - igl
  - iopath
  - nvidiacub
  - python
  - pytorch
  - pytorch3d
  - torchvision
  - pip
  - pip:
    - imageio
    - ipython
    - joblib
    - opencv-python
    - open3d
    - tensorboardx
    - git+https://github.com/mattloper/chumpy.git
    - lpips
    - scikit-image
    - matplotlib
